# Generated by Django 3.2.9 on 2021-12-01 11:48

import customers.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', customers.managers.CustomerManager()),
            ],
        ),
    ]
